--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Diduhless/TimeBomb
build-by-default: true
branches:
- master
projects:
  TimeBomb:
    path: ""
    icon: "icon.png"
    libs:
      - src: GiantQuartz/EasyUI/libEasyUI
        version: 1.0.0
...